### ISSUE TITLE
计算3D坐标的问题

### ISSUE THREAD

**Issue by FTJiang** [jingedawang/FeatureMethod#1]
您好，

请问一下怎样才能通过camera frame计算3D坐标呢？
您的代码里：
Mat K = ( Mat_<double> ( 3,3 ) << 520.9, 0, 325.1, 0, 521.0, 249.7, 0, 0, 1 );
这些点都是随意取的吗？有没有什么参考依据呢？

**Comment by jingedawang** [comment]
首先，K不是点，K是相机内参，每个相机的内参都是固定的，这与相机观测到的点没有关系。
其次，通过Camera frame计算3D坐标，你指的是计算相机的位姿还是计算特征点的3D位置呢？
如果是计算相机位姿，请看这篇文章http://www.jianshu.com/p/fbf56587a268
如果是计算特征点的3D位置，请看这篇文章http://www.jianshu.com/p/96d3b832330e

**Comment by zhujiawen1994** [comment]
> 您好，
> 
> 请问一下怎样才能通过camera frame计算3D坐标呢？
> 您的代码里：
> Mat K = ( Mat_ ( 3,3 ) << 520.9, 0, 325.1, 0, 521.0, 249.7, 0, 0, 1 );
> 这些点都是随意取的吗？有没有什么参考依据呢？

请问您的问题解决了吗？冒昧的问一句，你是想得到连续输入帧的每一帧图像的参数吗（例如R|t）?
