### ISSUE TITLE
输出问题

### ISSUE THREAD

**Issue by zhujiawen1994** [jingedawang/FeatureMethod#2]
请问该方法是否能获得每帧图像的参数？
最后输出得到的T指的是相邻两帧图像的转换矩阵吗？

**Comment by jingedawang** [comment]
每帧图像的参数是指什么？
最后输出的T是相邻两帧图像之间的转换矩阵。

**Comment by zhujiawen1994** [comment]
好，谢谢您！
另外我想咨询一下，您3d2d 和 3d3d的.cpp文件跑时是在Ubuntu下跑的还是Windows下跑的呢？两个系统下我都有尝试。Windows下g2o安装配置失败，不知您是否可以推荐一个教程步骤？Ubuntu下安装成功，但是运行.cpp 文件时，OpenCV的库函数使用没有问题，但是g2o下的库函数始终找不到，不知您是如何编译运行的，期待您的回复，真是黔驴技穷了，求指点！

**Comment by jingedawang** [comment]
我是在Ubuntu下跑的。我不知道你的g2o是怎么安装的，我是下载的g2o源码编译安装的，按照这里面的要求安装试一下https://github.com/RainerKuemmerle/g2o
