### ISSUE TITLE
三角测量-疑问

### ISSUE THREAD

**Issue by Hummel-Wang** [jingedawang/FeatureMethod#5]
博主，您好！我搭建了双目视觉系统，预想是获取2个具有特征的物体之间的空间位置信息，在学习过程中看到您的博客-三角测量栏目。现有几点疑问麻烦解惑，谢谢~
1.在文件triangulation.cpp中，triangulation函数中的T1/T2/K代表什么？
2.在文件triangulation.cpp中，main函数中的K代表什么？
3.在文件triangulation.cpp中，代码示例中所示“验证三角化点与特征点的重投影关系”功能模块中，4项输出能详细解释一下么？
4.在文件triangulation.cpp中，pose_estimation_2d2d 函数中求出的R/T跟双目视觉系统中的立体校正后得到的旋转矩阵、平移矩阵是对应的么？

**Comment by jingedawang** [comment]
1. `triangulation`函数的前提是已知相机在两个时刻的相对位姿，也就是参数`R`、`t`。`T1`是单位矩阵，代表相机在第一个时刻的位姿。`T2`是由`R`、`t`构造的矩阵，代表相机在第二个时刻的位姿。`K`代表相机的参数矩阵，也就是投影矩阵。
2. 文件中的所有`K`都代表相机的投影矩阵。该示例中，只有一个单目相机。
3. point in the first camera frame： 第一张图片上特征点的归一化相机坐标
point projected from 3D 3D点在第一张图上的归一化相机坐标， d=3D点相对于第一张图的深度
point in the second camera frame: 第二张图片上特征点的归一化相机坐标
point reprojected from second frame: 3D点在第二张图上的归一化相机坐标
4. 这个并没有对应关系。双目立体校正的目的是求出左目和右目间的相对位姿。而`pose_estimation_2d2d`函数中求出的`R`、`t`是单目相机在两个时刻的相对位姿。
